---
version: '3'
services:
  api-db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_TCP_PORT: 1433
      MSSQL_SA_PASSWORD: Emtec@321